def input_with_browser():
    return {"cookie":[
    {
        "domain": ".apollo.io",
        "expirationDate": 1741473916.724553,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "Qzp9G5gvZWPLXFvP57IhilMm71ulCh.cU4UnCrWNSKM-1741472116-1.0.1.1-G9Wz1.Xn0ZnUaYLzRr6IivF4K0XOeNv5G2psI0LzPffHfpjQ6Qi_KiUO__YzRC05Blr6g4RzV8G9G37newAxuk84d7FX0E5l3gSeowv1sE4",
        "id": 1
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "__hssrc",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": True,
        "storeId": "0",
        "value": "1",
        "id": 2
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757012601,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__hstc",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "21978340.3ef99bc8441b1e078734808617bc8360.1741452599958.1741452599958.1741460601480.2",
        "id": 3
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1775322815,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__qca",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "P0-1653720673-1741454015255",
        "id": 4
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772984999,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_cioanonid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "14aafcff-b1e3-37c7-de80-8d4afd9f9c49",
        "id": 5
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772986523,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_cioid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "67cc7b29e8d636000dad6acc",
        "id": 6
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772986415,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_clck",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "og9qr1%7C2%7Cfu1%7C0%7C1893",
        "id": 7
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1741536911,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_clsk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "xipttq%7C1741454111469%7C2%7C1%7Cw.clarity.ms%2Fcollect",
        "id": 8
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1776014110.724951,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GA1.1.667111217.1741454015",
        "id": 9
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1776014114.131672,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga_76XXTC73SP",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GS1.1.1741454014.1.1.1741454114.56.0.1550831006",
        "id": 10
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1.1.665096348.1741454014",
        "id": 11
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GCL.1741454015.Cj0KCQiA8q--BhDiARIsAP9tKI195x_idxDZSeDGBPGI6XWBh5wu3n08WwOx193gy_ypetzHeuXecSkaAnYoEALw_wcB",
        "id": 12
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_gs",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "2.1.k1$i1741454013$u118440665",
        "id": 13
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639521,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_grsmpkUhXtEvJi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 14
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639494,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gsxidUhXtEvJikyZ7",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 15
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772990110,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_hjSessionUser_3601622",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJpZCI6Ijc3NWI4NzZkLTE3NDYtNTdjOC1iNzU1LTFhZGM4MzdkMDQzMyIsImNyZWF0ZWQiOjE3NDE0NTQwMTUxNzIsImV4aXN0aW5nIjp0cnVlfQ==",
        "id": 16
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639429,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ps_partner_key_UhXtEvJi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 17
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639375,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ps_xid_UhXtEvJi_cwfP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 18
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1741540510,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_uetsid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ab3696f0fc4011efbe30a909cb3bebd4",
        "id": 19
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1775150110,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_uetvid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ab36d260fc4011efaffef7913e20e96b",
        "id": 20
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1773008117,
        "hostOnly": False,
        "httpOnly": False,
        "name": "amp_122a93",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1KNqzOdt0UclHG9ZbA4VEg.NjdjYzdiMjllOGQ2MzYwMDBkYWQ2YWNj.1.1ilrajo96.1ilrbvpsh.3.0.3",
        "id": 21
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772990015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "blueID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "e6a2cf01-1cbe-4893-8a89-7a5cad7e9536",
        "id": 22
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1744046015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "blueULC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 23
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "growSumoPartnerKey",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 24
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "gsxid",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 25
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757012601,
        "hostOnly": False,
        "httpOnly": False,
        "name": "hubspotutk",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "3ef99bc8441b1e078734808617bc8360",
        "id": 26
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1764802117,
        "hostOnly": False,
        "httpOnly": False,
        "name": "intercom-device-id-dyws6i9m",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "a7157787-74ea-47dd-939c-b100972d26c5",
        "id": 27
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1742076917,
        "hostOnly": False,
        "httpOnly": False,
        "name": "intercom-session-dyws6i9m",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "UVUyS29lUWRUUmVVczVYbmtFYjFRTWdZU202dy9wVmtESXVheEduSjI3dmkwdlllV0o4ZFpHSUg2Y2x5Y2RQK0IxZ09EdHRpUmJoS1NudHdJNlFSRlYrMGxSREZYZ1ZjZXgvd1RPSEVyaE09LS0rWkpwcm8xOFBuejMvQ0tFN2ZTeEtBPT0=--d506450fa32d4eb7c4be10dd97c2a632e3f515ab",
        "id": 28
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "ps_partner_key",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 29
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "ps_xid",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 30
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "pscd",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "get.apollo.io",
        "id": 31
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1744150516.724331,
        "hostOnly": False,
        "httpOnly": True,
        "name": "remember_token_leadgenie_v2",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqWTNZMk0zWWpJNVpUaGtOak0yTURBd1pHRmtObUZqWTE4M056STNNVEkwTjJabU1tVmxORE5oWWpCbFpEVTRZVGM0WkdWa05Ua3lOQ0k9IiwiZXhwIjoiMjAyNS0wNC0wOFQyMjoxNToxNi41NTBaIiwicHVyIjoiY29va2llLnJlbWVtYmVyX3Rva2VuX2xlYWRnZW5pZV92MiJ9fQ%3D%3D--ee33c9b4617a2d264915b35f977d65ed198445fe",
        "id": 32
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gclid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "Cj0KCQiA8q--BhDiARIsAP9tKI195x_idxDZSeDGBPGI6XWBh5wu3n08WwOx193gy_ypetzHeuXecSkaAnYoEALw_wcB",
        "id": 33
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gspk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "c2lkZGhhcnRoYmFnZ2E5NDEz",
        "id": 34
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gsxid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 35
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_landing_page",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "https://www.apollo.io/sign-up",
        "id": 36
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_referrer",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "https://www.google.com/",
        "id": 37
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_campaign",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "marketplace_siddharthbagga9413",
        "id": 38
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_gspartnerkey",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 39
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_medium",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "partner",
        "id": 40
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_source",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 41
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_campaign",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "marketplace_siddharthbagga9413",
        "id": 42
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_gspartnerkey",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 43
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_medium",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "partner",
        "id": 44
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_source",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 45
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757006122.38078,
        "hostOnly": False,
        "httpOnly": True,
        "name": "zp_device_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklsRXlhSGxpTWpGc1prVXhhRmt6ZURCTlZFNXJUVlJWZUU0eVozbFllbWhyV1ZkR2JVNXFSVEZOYW1NelRWWTVhVTV0V1RCTlJGWm9UVVJCTWsxcVVqaE5WR013VFZSUk1VNUVSWGxOWnowOUlnPT0iLCJleHAiOiIyMDI1LTA5LTA0VDE3OjE1OjIyLjA4NVoiLCJwdXIiOiJjb29raWUuenBfZGV2aWNlX2lkIn19--a0377f2a5fd05f1a0d72c6061a7986f7412f7edd",
        "id": 46
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "ZP_LATEST_LOGIN_PRICING_VARIANT",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "24Q4_UC_AA59_V2",
        "id": 47
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "ZP_Pricing_Split_Test_Variant",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "24Q4_UC_AA59_V2",
        "id": 48
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": True,
        "name": "_leadgenie_session",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "I0adwvXXNVidnj7D4lXMweaJEeBACRGaLU0R%2BRrj5sko0wW5HV2hpFqbazTHBK5bZVGRzM7hrSKC3iyKDkKHX%2B0dD%2BwQT0ltpvxJTywCjR6AR18g92owggp%2B1wZM0jQ0N7i0aSk%2Bs2W5wQqy1gyla5xMxXW2e8HCOx%2FgTkOBp%2FQdlL53tV56gIwBgrB8mSt0hvKJwab2aH7VUWi3Mvw9MOW%2F%2FP66MsM%2BcDEOCyeY5O77ByzPRvNRUN96cgihrpE98VjeKwW7qC0O%2FNaLrRhGAf5THmM723dzGgg%3D--u5uHBXu5JKu7gPMr--hXXF0bq%2FekGamuh6u3prhg%3D%3D",
        "id": 49
    },
    {
        "domain": "app.apollo.io",
        "expirationDate": 1775150438.628368,
        "hostOnly": True,
        "httpOnly": True,
        "name": "dwndvc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "b3e55977be9cabeb8ade76a930af6da61303038dc5e7af23054447be156f2448",
        "id": 50
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": True,
        "name": "dwnjrn",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "a6fd420011d5a64fd80d8a25688c0601414b1df85e7c3594a127145b20c64568",
        "id": 51
    },
    {
        "domain": "app.apollo.io",
        "expirationDate": 1741472716.724503,
        "hostOnly": True,
        "httpOnly": True,
        "name": "GCLB",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "COf0moinqPfUpAEQAw",
        "id": 52
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": False,
        "name": "X-CSRF-TOKEN",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "Jus6LVDqJXlVXXon8edrRU40kw-zN_ExI-jikf7bEY0ob9CVIdCzgZpqPstWn4yghCR_GXnS3F-9kH4rfKvfag",
        "id": 53
    }], "searchUrl": "https://app.apollo.io/#/people?finderViewId=5b8050d050a3893c382e9360&page=1&prospectedByCurrentTeam[]=no&contactEmailStatusV2[]=likely_to_engage&contactEmailStatusV2[]=verified&qKeywords=corporate%20banking&organizationIds[]=5f49727d63d39c0001f6693b&organizationIds[]=54a122df69702d7fe6374003",
      "startPage": 1,
      "waitForVerification": True,
    }