def input_with_browser():
    return {"cookie":[
    {
        "domain": ".apollo.io",
        "expirationDate": 1741462050.275215,
        "hostOnly": False,
        "httpOnly": True,
        "name": "__cf_bm",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "m_Rw9wkvGPWxwjJg3CQ7wMyILBvYQGWUNsk_Q1RSMB8-1741460250-1.0.1.1-dn5wId_bUIA..RmdmjzL5DpcOk79OIJVLJpRQFP2fA9VwhjSa2OrL2ToModYZXe2J1bvz0g5ovrMQxwyPPTePQQ0fmkzgTcDtoXFHcCs2lo",
        "id": 1
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1741462401,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__hssc",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "21978340.1.1741460601480",
        "id": 2
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "__hssrc",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": True,
        "storeId": "0",
        "value": "1",
        "id": 3
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757012601,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__hstc",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "21978340.3ef99bc8441b1e078734808617bc8360.1741452599958.1741452599958.1741460601480.2",
        "id": 4
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1775322815,
        "hostOnly": False,
        "httpOnly": False,
        "name": "__qca",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "P0-1653720673-1741454015255",
        "id": 5
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772984999,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_cioanonid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "14aafcff-b1e3-37c7-de80-8d4afd9f9c49",
        "id": 6
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772986523,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_cioid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "67cc7b29e8d636000dad6acc",
        "id": 7
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772986415,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_clck",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "og9qr1%7C2%7Cfu1%7C0%7C1893",
        "id": 8
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1741536911,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_clsk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "xipttq%7C1741454111469%7C2%7C1%7Cw.clarity.ms%2Fcollect",
        "id": 9
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1776014110.724951,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GA1.1.667111217.1741454015",
        "id": 10
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1776014114.131672,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ga_76XXTC73SP",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GS1.1.1741454014.1.1.1741454114.56.0.1550831006",
        "id": 11
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1.1.665096348.1741454014",
        "id": 12
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "GCL.1741454015.Cj0KCQiA8q--BhDiARIsAP9tKI195x_idxDZSeDGBPGI6XWBh5wu3n08WwOx193gy_ypetzHeuXecSkaAnYoEALw_wcB",
        "id": 13
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gcl_gs",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "2.1.k1$i1741454013$u118440665",
        "id": 14
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639521,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_grsmpkUhXtEvJi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 15
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639494,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_gsxidUhXtEvJikyZ7",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 16
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772990110,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_hjSessionUser_3601622",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJpZCI6Ijc3NWI4NzZkLTE3NDYtNTdjOC1iNzU1LTFhZGM4MzdkMDQzMyIsImNyZWF0ZWQiOjE3NDE0NTQwMTUxNzIsImV4aXN0aW5nIjp0cnVlfQ==",
        "id": 17
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639429,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ps_partner_key_UhXtEvJi",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 18
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230013.639375,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_ps_xid_UhXtEvJi_cwfP",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 19
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1741540510,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_uetsid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ab3696f0fc4011efbe30a909cb3bebd4",
        "id": 20
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1775150110,
        "hostOnly": False,
        "httpOnly": False,
        "name": "_uetvid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "ab36d260fc4011efaffef7913e20e96b",
        "id": 21
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772996602,
        "hostOnly": False,
        "httpOnly": False,
        "name": "amp_122a93",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "1KNqzOdt0UclHG9ZbA4VEg.NjdjYzdiMjllOGQ2MzYwMDBkYWQ2YWNj.1.1ilri7u8j.1ilri7u8j.3.0.3",
        "id": 22
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1772990015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "blueID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "e6a2cf01-1cbe-4893-8a89-7a5cad7e9536",
        "id": 23
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1744046015,
        "hostOnly": False,
        "httpOnly": False,
        "name": "blueULC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 24
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "growSumoPartnerKey",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 25
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "gsxid",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 26
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757012601,
        "hostOnly": False,
        "httpOnly": False,
        "name": "hubspotutk",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "3ef99bc8441b1e078734808617bc8360",
        "id": 27
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1764790602,
        "hostOnly": False,
        "httpOnly": False,
        "name": "intercom-device-id-dyws6i9m",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "a7157787-74ea-47dd-939c-b100972d26c5",
        "id": 28
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1742065402,
        "hostOnly": False,
        "httpOnly": False,
        "name": "intercom-session-dyws6i9m",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "Y0NJUnBObSt6M3pOYzl6MXRwSjE4dXZnNlRmbFM2aWVXeVpnWGpEUzllOTQ1Y09mM1VueTFIMm42MnRPQjYvbjZOV3dSemZjUjUrRllCS2NSdDNyTXFzOVI4MTFxSDZDU1NoelROL0E0eUk9LS1Ebkh6YlJQV1BVVHFmNDBEd0xkN3dnPT0=--35693b1045238a34cda4ac3909e9aafcbf6796b9",
        "id": 29
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "ps_partner_key",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 30
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "ps_xid",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 31
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1749230122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "pscd",
        "path": "/",
        "sameSite": "lax",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "get.apollo.io",
        "id": 32
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1744132838.626818,
        "hostOnly": False,
        "httpOnly": True,
        "name": "remember_token_leadgenie_v2",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklqWTNZMk0zWWpJNVpUaGtOak0yTURBd1pHRmtObUZqWTE4M056STNNVEkwTjJabU1tVmxORE5oWWpCbFpEVTRZVGM0WkdWa05Ua3lOQ0k9IiwiZXhwIjoiMjAyNS0wNC0wOFQxNzoyMDozOC40MzNaIiwicHVyIjoiY29va2llLnJlbWVtYmVyX3Rva2VuX2xlYWRnZW5pZV92MiJ9fQ%3D%3D--12ec14c513212b035fd22db8aa091ba7a20fab95",
        "id": 33
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gclid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "Cj0KCQiA8q--BhDiARIsAP9tKI195x_idxDZSeDGBPGI6XWBh5wu3n08WwOx193gy_ypetzHeuXecSkaAnYoEALw_wcB",
        "id": 34
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gspk",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "c2lkZGhhcnRoYmFnZ2E5NDEz",
        "id": 35
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__gsxid",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "hSBBUUCcIjobbJ",
        "id": 36
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_landing_page",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "https://www.apollo.io/sign-up",
        "id": 37
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_referrer",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "https://www.google.com/",
        "id": 38
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_campaign",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "marketplace_siddharthbagga9413",
        "id": 39
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_gspartnerkey",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 40
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_medium",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "partner",
        "id": 41
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__initial_utm_source",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 42
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_campaign",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "marketplace_siddharthbagga9413",
        "id": 43
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638122,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_gspartnerkey",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "siddharthbagga9413",
        "id": 44
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_medium",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "partner",
        "id": 45
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1746638014,
        "hostOnly": False,
        "httpOnly": False,
        "name": "zp__utm_source",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "affiliates_partnerstack",
        "id": 46
    },
    {
        "domain": ".apollo.io",
        "expirationDate": 1757006122.38078,
        "hostOnly": False,
        "httpOnly": True,
        "name": "zp_device_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "eyJfcmFpbHMiOnsibWVzc2FnZSI6IklsRXlhSGxpTWpGc1prVXhhRmt6ZURCTlZFNXJUVlJWZUU0eVozbFllbWhyV1ZkR2JVNXFSVEZOYW1NelRWWTVhVTV0V1RCTlJGWm9UVVJCTWsxcVVqaE5WR013VFZSUk1VNUVSWGxOWnowOUlnPT0iLCJleHAiOiIyMDI1LTA5LTA0VDE3OjE1OjIyLjA4NVoiLCJwdXIiOiJjb29raWUuenBfZGV2aWNlX2lkIn19--a0377f2a5fd05f1a0d72c6061a7986f7412f7edd",
        "id": 47
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "ZP_LATEST_LOGIN_PRICING_VARIANT",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "24Q4_UC_AA59_V2",
        "id": 48
    },
    {
        "domain": ".apollo.io",
        "hostOnly": False,
        "httpOnly": False,
        "name": "ZP_Pricing_Split_Test_Variant",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "24Q4_UC_AA59_V2",
        "id": 49
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": True,
        "name": "_leadgenie_session",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "%2FoypDO9KUb72YdiueLCui7Zmqx0gx7e38JlGf6zKD5YfPDPElOFdQgj2mEMAy3eUDRVT9UWSfUBzmcOJpNsMwyyB1lU%2BNOIRv6TQWJ88EUXp2CiRhi9C%2FmaGa9vebmfBipoRIcSprbzoiQAZtcUC92p9vncKsEcJYXxYNtCE8TviufVzRML7NanPeQCL8uis6kykg%2Bjh25s99QzgotHOT2QWbYA%2FIiwjyKIA5oFFdP0OI6RWaWYImcZcVxhblBkhS0NRT33COhsyw4BT3ki2nmuK9gjhVaXvee8%3D--U191GaqE%2FDlaM5ta--s2pkiwWdSVUXZW11kPzdsA%3D%3D",
        "id": 50
    },
    {
        "domain": "app.apollo.io",
        "expirationDate": 1775150438.628368,
        "hostOnly": True,
        "httpOnly": True,
        "name": "dwndvc",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": False,
        "storeId": "0",
        "value": "b3e55977be9cabeb8ade76a930af6da61303038dc5e7af23054447be156f2448",
        "id": 51
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": True,
        "name": "dwnjrn",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "a6fd420011d5a64fd80d8a25688c0601414b1df85e7c3594a127145b20c64568",
        "id": 52
    },
    {
        "domain": "app.apollo.io",
        "expirationDate": 1741460849.275169,
        "hostOnly": True,
        "httpOnly": True,
        "name": "GCLB",
        "path": "/",
        "sameSite": "unspecified",
        "secure": False,
        "session": False,
        "storeId": "0",
        "value": "CNX39cfr2tXpGBAD",
        "id": 53
    },
    {
        "domain": "app.apollo.io",
        "hostOnly": True,
        "httpOnly": False,
        "name": "X-CSRF-TOKEN",
        "path": "/",
        "sameSite": "lax",
        "secure": True,
        "session": True,
        "storeId": "0",
        "value": "DHGPeIruI2vSfyZXHXwm4gcpJAO8OwkpzR-CSntz7PcC9WXA-9S1kx1IYru6BMEHzTnIFXbeJEdTZx7w-QMiEA",
        "id": 54
    }], "searchUrl": "https://app.apollo.io/#/people?finderViewId=5b8050d050a3893c382e9360&page=1&prospectedByCurrentTeam[]=no&contactEmailStatusV2[]=likely_to_engage&contactEmailStatusV2[]=verified&qKeywords=corporate%20banking&organizationIds[]=5f49727d63d39c0001f6693b&organizationIds[]=54a122df69702d7fe6374003",
      "startPage": 1,
      "waitForVerification": True,
    }